// Per-trade image generation with Google Nano Banana Pro (Phase 3, §6 of PLAN.md).
//
// Generates the per-trade hero images (one per theme) from the crafted realism
// prompts in `prompts.ts`, then uploads them to the IMAGES R2 bucket at the key
// the renderer/ingest assigns (`trade/{theme}/hero.jpg`). Nano Banana Pro is
// Gemini's image model — automatable via the Generative Language REST API
// (unlike a web-only tool), so the only gate is a Gemini API key.
//
// Runs at ingest time (batch script), not in the Worker request path. The HTTP
// call is gated behind the key; `parseGeminiImageResponse` is the pure, tested
// unit. (This calls the Gemini API, not Claude — a separate provider by design.)

import type { ImagePrompt } from "./prompts.js";

/** Nano Banana Pro — Gemini 3 Pro Image (GA). Overridable via opts/env. */
export const IMAGE_MODEL = "gemini-3-pro-image";

export interface GeneratedImage {
  bytes: Uint8Array;
  mimeType: string;
}

/** Fold the avoid list into a single prompt string for the image model. */
export function composePrompt(p: ImagePrompt): string {
  return `${p.prompt}\n\nAvoid: ${p.negative}.`;
}

/** Minimal shape of the Gemini generateContent image response we read. */
interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        inlineData?: { mimeType?: string; data?: string };
        inline_data?: { mime_type?: string; data?: string };
      }>;
    };
  }>;
}

/** base64 → bytes, working in both Node 18+ and Workers (global atob). */
function base64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

/**
 * Extract the first inline image from a Gemini response. Tolerates both the
 * camelCase (`inlineData`) and snake_case (`inline_data`) shapes the API has
 * used. Throws a descriptive error if no image part is present.
 */
export function parseGeminiImageResponse(body: unknown): GeneratedImage {
  const res = body as GeminiResponse;
  const parts = res.candidates?.[0]?.content?.parts ?? [];
  for (const part of parts) {
    const inline = part.inlineData ?? part.inline_data;
    const data = inline?.data;
    if (data) {
      const mimeType =
        (part.inlineData?.mimeType ?? part.inline_data?.mime_type) || "image/png";
      return { bytes: base64ToBytes(data), mimeType };
    }
  }
  throw new Error("Gemini response contained no inline image data");
}

export interface GenerateImageOptions {
  apiKey: string;
  model?: string;
  /** Hero aspect — Nano Banana Pro honors imageConfig.aspectRatio. */
  aspectRatio?: string;
  baseUrl?: string;
  fetchImpl?: typeof fetch;
}

/**
 * Generate one image from a composed prompt via Nano Banana Pro. Returns the
 * raw bytes + mime type, ready for `uploadImage`.
 */
export async function generateImage(
  prompt: string,
  opts: GenerateImageOptions,
): Promise<GeneratedImage> {
  const model = opts.model ?? IMAGE_MODEL;
  const base = opts.baseUrl ?? "https://generativelanguage.googleapis.com";
  const doFetch = opts.fetchImpl ?? fetch;
  const url = `${base}/v1beta/models/${model}:generateContent?key=${encodeURIComponent(opts.apiKey)}`;

  const res = await doFetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        responseModalities: ["IMAGE"],
        imageConfig: { aspectRatio: opts.aspectRatio ?? "16:9" },
      },
    }),
  });
  if (!res.ok) {
    throw new Error(`Gemini ${res.status}: ${await res.text()}`);
  }
  return parseGeminiImageResponse(await res.json());
}

/** Upload generated bytes to the IMAGES R2 bucket at `key`. */
export async function uploadImage(
  bucket: R2Bucket,
  key: string,
  image: GeneratedImage,
): Promise<void> {
  await bucket.put(key, image.bytes, {
    httpMetadata: { contentType: image.mimeType },
  });
}
